### ISSUE TITLE
ghuser/repo defaults should not break plugin

### ISSUE THREAD

**Issue by softprops** [softprops/ls#32]
reported on sbt list. don't assume git is on the users path.

[info] Loading global plugins from /Users/hhrutz/.sbt/plugins
[info] Loading project definition from /Users/hhrutz/Documents/devel/ScalaOSC/project
[error] java.io.IOException: Cannot run program "git": error=2, No such file or directory
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? last
[info] Loading global plugins from /Users/hhrutz/.sbt/plugins
[debug]
[debug] Initial source changes:
[debug]         removed:Set()
[debug]         added: Set()
[debug]         modified: Set()
[debug] Removed products: Set()
[debug] Modified external sources: Set()
[debug] Modified binary dependencies: Set()
[debug] Initial directly invalidated sources: Set()
[debug]
[debug] Sources indirectly invalidated by:
[debug]         product: Set()
[debug]         binary dep: Set()
[debug]         external source: Set()
[debug] Initially invalidated: Set()
[debug] Copy resource mappings:
[debug]
[debug] Other repositories:
[debug] Default repositories:
[debug]         URLRepository(typesafe-ivy-releases,sbt.Patterns@92eb86)
[debug]         Raw(ProjectResolver(inter-project, mapped: ))
[debug]         FileRepository(local,FileConfiguration(true,None),sbt.Patterns@e0bfc9)
[debug]         sbt-idea-repo: http://mpeltonen.github.com/maven/
[debug]         public: http://repo1.maven.org/maven2/
[debug]         Scala-Tools Maven2 Repository: http://scala-tools.org/repo-releases
[debug] Using inline dependencies specified in Scala.
[debug] post 1.3 ivy file: using exact as default matcher
[info] Loading project definition from /Users/hhrutz/Documents/devel/ScalaOSC/project
[debug]
[debug] Initial source changes:
[debug]         removed:Set()
[debug]         added: Set()
[debug]         modified: Set()
[debug] Removed products: Set()
[debug] Modified external sources: Set()
[debug] Modified binary dependencies: Set()
[debug] Initial directly invalidated sources: Set()
[debug]
[debug] Sources indirectly invalidated by:
[debug]         product: Set()
[debug]         binary dep: Set()
[debug]         external source: Set()
[debug] Initially invalidated: Set()
[debug] Copy resource mappings:
[debug]
java.io.IOException: Cannot run program "git": error=2, No such file or directory
       at java.lang.ProcessBuilder.start(ProcessBuilder.java:460)
       at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:380)
       at sbt.AbstractProcessBuilder.lines(ProcessImpl.scala:155)
       at sbt.AbstractProcessBuilder.lines_$bang(ProcessImpl.scala:150)
       at ls.Plugin$.maybeRepo(ls.scala:455)
       at ls.Plugin$$anonfun$lsPublishSettings$14.apply(ls.scala:405)
       at ls.Plugin$$anonfun$lsPublishSettings$14.apply(ls.scala:405)
       at sbt.Init$Value$$anonfun$apply$5.apply(Settings.scala:309)
       at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:151)
       at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:151)
       at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:170)
       at sbt.EvaluateSettings$INode.evaluate(INode.scala:126)
       at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:61)
       at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:70)
       at sbt.EvaluateSettings$$anon$3.run(INode.scala:66)
       at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
       at java.lang.Thread.run(Thread.java:637)
Caused by: java.io.IOException: error=2, No such file or directory
       at java.lang.UNIXProcess.forkAndExec(Native Method)
       at java.lang.UNIXProcess.<init>(UNIXProcess.java:53)
       at java.lang.ProcessImpl.start(ProcessImpl.java:91)
       at java.lang.ProcessBuilder.start(ProcessBuilder.java:453)
       at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:380)
       at sbt.AbstractProcessBuilder.lines(ProcessImpl.scala:155)
       at sbt.AbstractProcessBuilder.lines_$bang(ProcessImpl.scala:150)
       at ls.Plugin$.maybeRepo(ls.scala:455)
       at ls.Plugin$$anonfun$lsPublishSettings$14.apply(ls.scala:405)
       at ls.Plugin$$anonfun$lsPublishSettings$14.apply(ls.scala:405)
       at sbt.Init$Value$$anonfun$apply$5.apply(Settings.scala:309)
       at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:151)
       at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:151)
       at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:170)
       at sbt.EvaluateSettings$INode.evaluate(INode.scala:126)
       at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:61)
       at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:70)
       at sbt.EvaluateSettings$$anon$3.run(INode.scala:66)
       at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
       at java.lang.Thread.run(Thread.java:637)

this is a real show stopper for me, since all my projects rely on using the sbt integration of IDEA. if i run sbt from a terminal, there seems to be no problem with git lookup.

my settings are in this case:

seq( lsSettings :_\* )

(LsKeys.tags in LsKeys.lsync) := Seq( "osc", "open-sound-control", "sound", "network" )

(description in LsKeys.lsync) := "A library for OpenSoundControl (OSC), a message protocol used in multi-media applications."

// (LsKeys.ghUser in LsKeys.lsync) := Some( "Sciss" )

// (LsKeys.ghRepo in LsKeys.lsync) := Some( "ScalaOSC" )

(i commented out the github stuff, since i wasn't sure it was involved in ls trying to run 'git').

**Comment by softprops** [comment]
link to thread - https://groups.google.com/group/simple-build-tool/browse_thread/thread/4538a97f3e4d1f30/94e792042fa2899d#94e792042fa2899d

**Comment by eed3si9n** [comment]
I just hit this one too opening sbt from IDEA. It just said 

```
[error] java.io.IOException: Cannot run program "git": error=2, No such file or directory
```

so at first I was kind of confused. When I displayed the stack trace `at ls.Plugin$.maybeRepo(ls.scala:455)` showed up and I remembered the thread from the sbt list.

**Comment by softprops** [comment]
Okay. Are you on windows. I was thinking of doing another release the night after tomorrow. Tomorrows ny-scala workshop night. Eric pointed out [this](https://github.com/gseitz/sbt-release/issues/6) to me which I'm going to borrow from. Basically detect windows first and use git.exe and fallback on git. If all else fails just try catch it returning None. I realize I should have just done that to start with. Git's should not even be a requirement for this plugin (yet). I just use it to check for a gh origin for which I can extract your gh user and repo from. Look for a release with a fix for this and the licences thing the night after tomorrow. Maybe even tomorrow depending on how long this work shop goes.   

I wanted to say thanks for using the plugin. I really want the plugin to provide a solid user experience (which I think I failed my first attempt at) I think once some things get ironed out it could help change the way we (the scala community) does business. By business I mean getting straight the the fun part, coding. If you have any ideas let me know.

**Comment by eed3si9n** [comment]
IDEA running on Mac. [I added a similar bug](https://github.com/n8han/conscript/issues/31) to giter8/conscript when I adopted the gitnub convention.
It turns out that API v2 token is not even supported on v3 because it requires OAuth token (it could be programmatically generated but requires plain password to do so).

We the community thank you for this work!

**Comment by softprops** [comment]
Thanks. On that note... last commit of the night

https://github.com/eed3si9n/dispatch-github/pull/1

```
scala> dispatch.github.OAuth.accessToken("xxx", "xxx") match {
  |   case Some(token) => dispatch.Http(dispatch.github.OAuthClient(token)(dispatch.github.Repos("eed3si9n", "sff4s").git_refs) as_str)
  |   case _ => "no dice"
  | }
 INF: [console logger] dispatch: api.github.com GET /repos/eed3si9n/sff4s/git/refs?access_token=16e72b4e7217dc191f72bc9ca0ca0c9072c746a3 HTTP/1.1
 res1: dispatch.Http.HttpPackage[String] = [{"url":"https://api.github.com/repos/eed3si9n/sff4s/git/refs/heads/master","object":{"type":"commit","sha":"52638262567a20e1a8dce157d8d204a6a422c031","url":"https://api.github.com/repos/eed3si9n/sff4s/git/commits/52638262567a20e1a8dce157d8d204a6a422c031"},"ref":"refs/heads/master"}]
```

**Comment by softprops** [comment]
should be fixed now
