### ISSUE TITLE
Bad luck on first run (NoClassDefFoundError: org/apache/http/HttpHost)

### ISSUE THREAD

**Issue by iaraknes** [softprops/ls#66]
First thing after installing with
$ cs softprops/ls

$ lsinit
java.lang.NoClassDefFoundError: org/apache/http/HttpHost
        at dispatch.$colon$div$.apply(requests.scala:249)
        at ls.LsInit$.lsVersion(init.scala:38)
        at ls.LsInit$.run(init.scala:15)
        at ls.LsInit.run(init.scala:94)
        at ls.LsInit.run(init.scala:92)
        at xsbt.boot.Launch$.run(Launch.scala:54)
        at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:43)
        at xsbt.boot.Launch$.launch(Launch.scala:68)
        at xsbt.boot.Launch$.apply(Launch.scala:14)
        at xsbt.boot.Boot$.runImpl(Boot.scala:25)
        at xsbt.boot.Boot$.main(Boot.scala:15)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.http.HttpHost
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        ... 12 more
Error during sbt execution: java.lang.NoClassDefFoundError: org/apache/http/HttpHost

**Comment by softprops** [comment]
thanks for reporting. Ill look into it.
