### ISSUE TITLE
2.2.0 does _not_ work with scala 2.10.0

### ISSUE THREAD

**Issue by WellRedPandit** [softprops/ls#68]
Exception at the bottom. 
Gradle tells me scalatra transitively depends on scala-lib 2.9.2. As far as I can tell grizzled is the cause of the exception. However, when I tried to hand-pick dependencies upping grizzled to 2.10:1.0.1, the exception was stil there.

**Gradle**

```
+--- org.scalatra:scalatra:2.2.0
|    +--- org.scalatra:scalatra-common:2.2.0
|    |    \--- org.scala-lang:scala-library:2.9.2 -> 2.10.0
|    +--- org.scala-lang:scala-library:2.9.2 -> 2.10.0
|    +--- org.clapper:grizzled-slf4j_2.9.2:0.6.10
|    |    +--- org.scala-lang:scala-library:2.9.2 -> 2.10.0
|    |    \--- org.slf4j:slf4j-api:1.7.1
|    +--- org.scalatra.rl:rl_2.9.2:0.4.2
|    |    \--- org.scala-lang:scala-library:2.9.2 -> 2.10.0
|    +--- com.googlecode.juniversalchardet:juniversalchardet:1.0.3
|    +--- eu.medsea.mimeutil:mime-util:2.1.3
|    |    \--- org.slf4j:slf4j-api:1.5.6 -> 1.7.1
|    +--- joda-time:joda-time:2.1
|    +--- org.joda:joda-convert:1.2
|    \--- com.typesafe.akka:akka-actor:2.0.5
|         +--- org.scala-lang:scala-library:2.9.2 -> 2.10.0
|         \--- com.typesafe:config:0.3.1 -> 1.0.0
```

**Handpicked deps** (same exception)

```
// underscored, otherwise easy to confuse with scalaVersion
def scalaVersionMajor = '2.10'
def scalatra_version = '2.2.0'
libraries.scalatra = [
"org.scalatra:scalatra:${scalatra_version}@jar",
"org.scalatra:scalatra-common:${scalatra_version}@jar",
"org.clapper:grizzled-slf4j_${scalaVersionMajor}:1.0.1@jar",
"org.scalatra.rl:rl_${scalaVersionMajor}:0.4.2@jar",
"org.scalatra:scalatra-slf4j_${scalaVersionMajor}:${scalatra_version}@jar",
```

**Exception**

```
Exception in thread "main" java.lang.NoClassDefFoundError: scala/reflect/Manifest$
    at org.scalatra.servlet.ScalatraListener.<init>(ScalatraListener.scala:14)
    at gmo.quantbridge.web.JettyServer.<init>(jetty.scala:17)
    at gmo.quantbridge.web.JettyServer$.main(jetty.scala:61)
    at gmo.quantbridge.web.JettyServer.main(jetty.scala)
Caused by: java.lang.ClassNotFoundException: scala.reflect.Manifest$
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 4 more
```

**Comment by softprops** [comment]
Can you tell me what about ls would be an issue here? ls is an sbt plugin that generates project metadata and uses hosted metadata to append library dependencies. Class not found sounds like a class path and or faulty artifact issue.

**Comment by WellRedPandit** [comment]
Boy, does it suck to be a novice on github :-) It's a scalatra issue, not ls. I followed the wrong link. Terribly sorry. Will proceed to the right place now.
