### ISSUE TITLE
ls-sbt on sbt 0.13 pulls dispatch _2.9.1 and _2.10

### ISSUE THREAD

**Issue by eed3si9n** [softprops/ls#71]
### steps

use ls-sbt on sbt 0.13.0-RC3.

inside `project/build.properties`:

```
sbt.version=0.13.0-RC3
```

inside `project/ls.sbt`:

``` scala
resolvers ++= Seq("coda" at "http://repo.codahale.com")

addSbtPlugin("me.lessis" % "ls-sbt" % "0.1.2")
```
### problem

```
[error] Modules were resolved with conflicting cross-version suffixes in {file:/Users/eed3si9n/work/quick-demo/sbt-lstest/project/}sbt-lstest-build:
[error]    net.databinder:dispatch-core _2.9.1, _2.10
[error]    net.databinder:dispatch-http _2.9.1, _2.10
[error]    net.databinder:dispatch-futures _2.9.1, _2.10
java.lang.RuntimeException: Conflicting cross-version suffixes in: net.databinder:dispatch-core, net.databinder:dispatch-http, net.databinder:dispatch-futures
    at scala.sys.package$.error(package.scala:27)
    at sbt.ConflictWarning$.processCrossVersioned(ConflictWarning.scala:47)
    at sbt.ConflictWarning$.apply(ConflictWarning.scala:30)
    at sbt.Classpaths$$anonfun$61.apply(Defaults.scala:1027)
    at sbt.Classpaths$$anonfun$61.apply(Defaults.scala:1027)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:244)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:680)
[error] (*:update) Conflicting cross-version suffixes in: net.databinder:dispatch-core, net.databinder:dispatch-http, net.databinder:dispatch-futures
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```
### expectation

the build works.

**Comment by eed3si9n** [comment]
never mind. this could be coming from some other plugin.

**Comment by softprops** [comment]
I'm going to reopen. I saw your post last night and did a quick look. I'm not sure if its me or not but I am using dispatch classic instead of reboot. I'm going to try and use this opportunity and refactor to reboot 0.11.0. Then I'll def be sure its not me. reboot is not published for < 2.9.3 :)

Thanks again for your very through and detailed bug reports. If anyone is a professional in this community, it's you.

**Comment by Sciss** [comment]
Is this related? I'm only getting an error, like this:

```
$ sbt lsync
...
[info] lsyncing project Sciss/ScalaCollider@1.10.0...
java.lang.NoSuchMethodError: dispatch.url$.apply(Ljava/lang/String;)Ldispatch/Req;
    at ls.Client.api(client.scala:14)
    at ls.Client.lsync(client.scala:41)
    at ls.Plugin$$anonfun$lsyncTask$1.apply(ls.scala:102)
    at ls.Plugin$$anonfun$lsyncTask$1.apply(ls.scala:95)
    at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:35)
    at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:34)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:244)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
at java.lang.Thread.run(Thread.java:680)
```

(sbt 0.13.0, ls 0.1.3)

**Comment by Sciss** [comment]
Nothing?

**Comment by eed3si9n** [comment]
I haven't had this problem since I updated to ls-sbt 0.1.3.

**Comment by softprops** [comment]
yes. please upgrade to 0.1.3

**Comment by Sciss** [comment]
Ok, yes I was using ls-sbt 0.1.3 already.

I found the culprit now:

```
addSbtPlugin("com.typesafe.sbt" % "sbt-pgp" % "0.8")
```

This produces the problem with 2.9 version of Dispatch. The problem disappears with the update

```
addSbtPlugin("com.typesafe.sbt" % "sbt-pgp" % "0.8.1")
```

I guess you can close the issue now.
